### ISSUE TITLE
Implement Python output

### ISSUE THREAD

**Issue by cuducos** [datopian/jsv#11]
API-driven design hint:

```console
$ jsv --template=... {schema-url} > mypython.py
```

The idea is to generate code useful in [`ckan-client-py`](https://github.com/datopian/ckan-client-py#developers), for example.

A possible road-map:

* [x] `jsv` with template option
* [x] Create template for Python

LATER

* [ ] **LATER** Embed this stuff in [`ckan-client-guide`](https://github.com/datopian/ckan-client-guide)
  * [ ] **LATER** maybe look at VuePress for this (or even consider adding it to tech.datopian.com)

Python file draft ([also check `ckan-client-guide` related issue](https://github.com/datopian/ckan-client-guide/issues/3#event-3685251906)):

```python
dataset_dict = {
  # ...
  'name': 'example value'
  'license': ...
  'number_of_downloads': ...
  'path': 'string'
  # 'path': [ ... ]
}

# full example
dataset = Dataset(dataset_dict)
client = ckanclient.Client()
client.push(Dataset)
```

**Comment by rufuspollock** [comment]
@cuducos i've moved the ckanext-scheming work to #13. The Later stuff here is really part of ckan-client-guide so should move there. And then we can close this issue.

**Comment by cuducos** [comment]
Ok, so I think #12 should have closed this issue : )
