### ISSUE TITLE
Differences between JSON from Frictionless data and other schemas

### ISSUE THREAD

**Issue by cuducos** [datopian/jsv#9]
I have seen `choices` in JSON Schemas while pairing with @mariorodeghiero , but

1. I couldn't find its specification and 
1. as far as I understood from [this issue](https://github.com/json-schema-org/json-schema-spec/issues/57) it was discarded in favor of a particular use case of `oneOf`.

Also, I have also seen `resource_fields` and I couldn't find the specs for that.

Maybe the JSON we (Mario and I) were discussing is not a _strict_ JSON Schema. If that is the case, should we support fields like that (`choice` and `resource_fields` on these examples)?

How will that relate to JSON Schema specs implemented and planned so far?

**Comment by rufuspollock** [comment]
INVALID. The schema you were looking at was not a JSON Schema.
